from typing import List, Dict, Any

from drf_to_ninja.parsers.permissions import DRF_TO_NINJA_PERMISSIONS, DRF_TO_NINJA_AUTH


def generate_auth(permissions_data: List[Dict[str, Any]]) -> str:
    output = "from ninja.security import HttpBearer, django_auth, HttpBasicAuth\n\n"

    for entry in permissions_data:
        view = entry["view"]
        kind = entry["type"]
        classes = entry["classes"]

        output += f"# --- {kind.title()} for {view} ---\n"

        if kind == "authentication":
            for cls in classes:
                ninja_equiv = DRF_TO_NINJA_AUTH.get(cls)
                if ninja_equiv:
                    output += f"# DRF {cls} -> Ninja {ninja_equiv}\n"
                else:
                    output += f"# ⚠️ USER REVIEW REQUIRED: No direct Ninja equivalent for {cls}\n"

        elif kind == "permission":
            for cls in classes:
                ninja_equiv = DRF_TO_NINJA_PERMISSIONS.get(cls)
                if ninja_equiv:
                    output += f"# DRF {cls} -> auth={ninja_equiv}\n"
                else:
                    output += f"# ⚠️ USER REVIEW REQUIRED: Custom permission '{cls}' needs manual porting\n"

        output += "\n"

    return output


def generate_settings_report(settings_data: Dict[str, Any]) -> str:
    output = "# DRF Settings Migration Report\n"
    output += "# Generated by drf2ninja\n\n"

    pagination = settings_data.get("pagination", {})
    if pagination:
        page_class = pagination.get("DEFAULT_PAGINATION_CLASS", "")
        page_size = pagination.get("PAGE_SIZE", 10)
        output += "# --- Pagination ---\n"
        output += f"# DRF: {page_class} (PAGE_SIZE={page_size})\n"
        output += "# Ninja: Use ninja.pagination.paginate + LimitOffsetPagination or PageNumberPagination\n"
        output += f"from ninja.pagination import paginate, LimitOffsetPagination\n\n"
        output += f"# Apply @paginate to your endpoint and set page_size={page_size}\n\n"

    auth_classes = settings_data.get("authentication", [])
    if auth_classes:
        output += "# --- Default Authentication ---\n"
        for cls in auth_classes:
            short = cls.split(".")[-1] if "." in cls else cls
            ninja_equiv = DRF_TO_NINJA_AUTH.get(short, "USER REVIEW REQUIRED")
            output += f"# DRF: {cls} -> Ninja: {ninja_equiv}\n"
        output += "\n"

    perm_classes = settings_data.get("permissions", [])
    if perm_classes:
        output += "# --- Default Permissions ---\n"
        for cls in perm_classes:
            short = cls.split(".")[-1] if "." in cls else cls
            ninja_equiv = DRF_TO_NINJA_PERMISSIONS.get(short, "Custom — manual porting needed")
            output += f"# DRF: {cls} -> Ninja: {ninja_equiv}\n"
        output += "\n"

    throttle = settings_data.get("throttling", {})
    if throttle:
        output += "# --- Throttling ---\n"
        output += "# ⚠️ USER REVIEW REQUIRED:\n"
        output += "# Django Ninja does not have built-in throttling.\n"
        output += "# Consider using django-ninja-extra or custom middleware.\n"
        for k, v in throttle.items():
            output += f"# DRF: {k} = {v}\n"
        output += "\n"

    filters = settings_data.get("filtering", [])
    if filters:
        output += "# --- Filter Backends ---\n"
        output += "# ⚠️ USER REVIEW REQUIRED:\n"
        output += "# Django Ninja uses Query parameters and FilterSchema instead of DRF filter backends.\n"
        for f in filters:
            output += f"# DRF: {f}\n"
        output += "# Ninja: Use FilterSchema or manual query params\n\n"

    raw = settings_data.get("raw", {})
    if raw:
        output += "# --- Other Settings ---\n"
        for k, v in raw.items():
            output += f"# {k} = {v}\n"
        output += "\n"

    return output
